name: flutter_country_selector
description: how a country picker to select a country
version: 1.0.9
repository: https://github.com/cedvdb/flutter_country_selector
homepage: https://github.com/cedvdb/flutter_country_selector

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ">=0.18.0 <=1.0.0"
  diacritic: ^0.1.5
  circle_flags: ^5.0.0
  # for iso codes, phone_numbers_parser needs to stay currently
  # as the flutter_country_selector library needs to be
  # compatible with phone_form_field
  phone_numbers_parser: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  generate: true
